stages:
    - build
    - package
        
build app:
    stage: build
    script:
        - mvn clean compile test-compile
    tags:
        - maven

build docker image:
    stage: package
    script:
        - mvn clean package -DskipTests docker:build
    tags: 
        - maven
        - docker
    only:
        - develop
