spring:
  application:
    name: eureka-registry
  profiles:
    active: production

server:
  port: 8282

eureka:
  server:
    max-threads-for-peer-replication: 0
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      default-zone: http://eureka-registry:8282/eureka