spring:
  application:
    name: projects-api
  profiles:
    active: production
  data:
    mongodb:
      uri: mongodb://mongodb:27017/projects-api

server:
  port: 8183
  context-path: /projects-api

eureka:
  instance:
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://eureka-registry:8282/eureka