spring:
  application:
    name: gateway-service
server:
  port: 8662
    
eureka:
  instance:
    prefer-ip-address: false
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-registry:8282/eureka

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
        timeout:
            enabled: false

zuul:
  ignoredServices: '*'
  add-host-header: true
  add-proxy-headers: true
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
  routes:
    projects-api:
      path: /projects-api/**
      service-id: projects-api
      strip-prefix: false
      sensitive-headers:
